# Generated by Django 3.2.5 on 2021-12-17 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=200)),
                ('superv_name', models.CharField(max_length=200)),
                ('project_catg', models.CharField(choices=[('Web Project', 'Web Project'), ('Mobile App Dev Project', 'Mobile App Dev Project'), ('Machine Learning Project', 'Machine Learning Project'), ('Project', 'Project')], max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('individual', models.BooleanField(default=False)),
                ('grouped', models.BooleanField(default=False)),
                ('member', models.CharField(max_length=2)),
            ],
        ),
    ]
