# Generated by Django 3.2.5 on 2021-12-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plep_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
