# Generated by Django 3.2.5 on 2021-12-22 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plep_app', '0003_client_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='fullname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='member',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='project_catg',
            field=models.CharField(blank=True, choices=[('Web Project', 'Web Project'), ('Mobile App Dev Project', 'Mobile App Dev Project'), ('Machine Learning Project', 'Machine Learning Project'), ('Project', 'Project')], max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='superv_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.CharField(blank=True, default=uuid.UUID('c49e8228-d036-4a9b-bb9e-d95bdfb962fc'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
