# Generated by Django 3.2.5 on 2021-12-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plep_app', '0005_alter_client_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
