# Generated by Django 3.2.5 on 2021-12-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plep_app', '0006_client_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.CharField(default='753d4014', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
