# Generated by Django 3.2.5 on 2021-12-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plep_app', '0008_alter_client_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.UUIDField(default='alto8YUeeh', editable=False, primary_key=True, serialize=False),
        ),
    ]
