# Generated by Django 3.2.5 on 2021-12-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plep_app', '0009_alter_client_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.CharField(default='29A8EVaA2C', max_length=10, primary_key=True, serialize=False),
        ),
    ]
